name: Run Code

on:
  workflow_dispatch:

jobs:
  run-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print Hello
        run: echo "Hello, your workflow is working!"
